name: Push latest

on:
  push:
    branches:
      - master

jobs:
  push:
    name: Push latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: mr-smithers-excellent/docker-build-push@v2
        with:
          image: tktcorporation/selenium-crystal
          tag: latest
          registry: index.docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
